version: "2"

services:
  cron:
    restart: always
    build:
      context: docker/crond
    volumes:
      - cert:/etc/ssl/acme
      - logs/cron:/var/log/cron
  proxy:
    restart: always
    build:
      context: docker/nginix-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - common/conf/nginx:/etc/nginx
      - cert:/etc/ssl/acme
      - logs/nginx:/var/log/nginx
